@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":QuickCacheParser" as QuickCacheParser LOGIC_COLOR
participant ":AddCommandParser" as AddCommandParser LOGIC_COLOR
participant "t:AddCommand" as AddCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant "lastShownList:ObservableList<Flashcard>" as ObservableList MODEL_COLOR
participant "flashcard:Flashcard" as Flashcard MODEL_COLOR
participant "updatedFlashcard:Flashcard" as UpdatedFlashcard MODEL_COLOR
end box
[-> LogicManager : execute(test 1 ans/Example answer)
activate LogicManager

LogicManager -> QuickCacheParser : parseCommand(add q/question ans/ Answer)
activate QuickCacheParser

create AddCommandParser
QuickCacheParser -> AddCommandParser
activate AddCommandParser

AddCommandParser -> QuickCacheParser
deactivate AddCommandParser

QuickCacheParser -> AddCommandParser : parse(q/question ans/Example Answer)
activate AddCommandParser

create AddCommand
AddCommandParser -> AddCommand
activate AddCommand

AddCommand --> AddCommandParser : t
deactivate AddCommand

AddCommandParser -> QuickCacheParser : t
deactivate AddCommandParser

'Hidden arrow to position the destroy marker below the end of the activation bar.
AddCommandParser -[hidden]-> QuickCacheParser
destroy AddCommandParser

QuickCacheParser --> LogicManager : t
deactivate QuickCacheParser

LogicManager -> AddCommand : execute()
activate AddCommand

TestCommand -> Model : getFilteredFlashcardList()
activate Model

Model -> ObservableList
activate ObservableList

ObservableList -> Model
deactivate ObservableList

Model --> TestCommand : lastShownList
deactivate Model

TestCommand -> ObservableList : get(index)
activate ObservableList

ObservableList -> Flashcard
activate Flashcard

Flashcard -> ObservableList
deactivate Flashcard

ObservableList -> TestCommand : flashcard
deactivate ObservableList

TestCommand -> Flashcard : checkAnswer(answer)
activate Flashcard

Flashcard -> TestCommand : isCorrect
deactivate Flashcard

alt is correct

    TestCommand -> Flashcard : getFlashcardAfterTestSuccess()
    activate Flashcard

    create UpdatedFlashcard
    Flashcard -> UpdatedFlashcard : getFlashcardAfterTestSuccess()
    activate UpdatedFlashcard

    UpdatedFlashcard -> Flashcard
    deactivate UpdatedFlashcard

    Flashcard -> TestCommand : updatedFlashcard
    deactivate Flashcard

else is not correct

   TestCommand -> Flashcard : getFlashcardAfterTestFailure()
   activate Flashcard

   create UpdatedFlashcard
   Flashcard -> UpdatedFlashcard : getFlashcardAfterTestFailure()
   activate UpdatedFlashcard

   UpdatedFlashcard -> Flashcard
   deactivate UpdatedFlashcard

   Flashcard -> TestCommand : updatedFlashcard
   deactivate Flashcard

end

TestCommand -> Model : setFlashcard(f, updated)
activate Model

Model -> Flashcard
activate Flashcard

Flashcard -> Model
destroy Flashcard

Model -> TestCommand
deactivate Model

TestCommand --> LogicManager : result
deactivate TestCommand
TestCommand -[hidden]-> LogicManager : result
destroy TestCommand

[<--LogicManager
deactivate LogicManager
@enduml